# Generated by Django 5.2.1 on 2025-06-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='talleres', to='cursos.alumno')),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talleres', to='clientes.colegio')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talleres', to='cursos.curso')),
            ],
        ),
    ]
