# Generated by Django 5.2.1 on 2025-07-03 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('talleres', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taller',
            options={'ordering': ['nombre'], 'verbose_name': 'Taller', 'verbose_name_plural': 'Talleres'},
        ),
        migrations.AlterField(
            model_name='taller',
            name='colegio',
            field=models.ForeignKey(blank=True, help_text='Colegio al que pertenece este taller', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talleres', to='clientes.colegio'),
        ),
    ]
