# Generated by Django 5.2.1 on 2025-07-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_alter_taller_options_alter_taller_colegio'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='numero_sesiones',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de días/sesiones que se espera realizar en este taller', verbose_name='Número de sesiones planificadas'),
        ),
    ]
