# Generated by Django 5.2.1 on 2025-06-04 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='coordinador',
            field=models.ForeignKey(limit_choices_to={'rol': 'coordinador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colegios_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dueno',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dueno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colegio',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colegios', to='clientes.dueno'),
        ),
    ]
