# Generated by Django 5.2.1 on 2025-06-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(choices=[('basica', 'Básica'), ('media', 'Media')], max_length=10)),
                ('grado', models.PositiveSmallIntegerField(help_text='1–8 si es Básica, 1–4 si es Media')),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='clientes.colegio')),
            ],
            options={
                'ordering': ['colegio', 'ciclo', 'grado'],
                'unique_together': {('colegio', 'ciclo', 'grado')},
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='cursos.curso')),
            ],
        ),
    ]
