# Generated by Django 5.2.1 on 2025-07-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='ciclo',
            field=models.CharField(choices=[('basica', 'Básica'), ('media', 'Media'), ('ADULTOS_BASICA', 'Educación de Adultos - Básica'), ('ADULTOS_MEDIA', 'Educación de Adultos - Media')], max_length=20),
        ),
    ]
