# Generated by Django 5.2.4 on 2025-07-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_colegio_coordinador_alter_colegio_direccion_and_more'),
        ('cursos', '0002_alter_curso_ciclo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['curso__colegio__nombre', 'curso__ciclo', 'curso__grado', 'curso__seccion', 'nombre'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['colegio__nombre', 'ciclo', 'grado', 'seccion'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='A', help_text='Letra de la sección (A, B, C…)', max_length=1),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ciclo',
            field=models.CharField(choices=[('basica', 'Básica'), ('media', 'Media'), ('ADULTOS_BASICA', 'Educación de Adultos – Básica'), ('ADULTOS_MEDIA', 'Educación de Adultos – Media')], max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='grado',
            field=models.PositiveSmallIntegerField(help_text='1–8 si es Básica; 1–4 si es Media'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('colegio', 'ciclo', 'grado', 'seccion')},
        ),
    ]
