# Generated by Django 5.2.1 on 2025-07-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_colegio_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('cliente', 'Cliente'), ('supervisor', 'Supervisor')], max_length=30),
        ),
    ]
