# Generated by Django 5.2.1 on 2025-06-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('F', 'Falta')], max_length=1)),
            ],
            options={
                'ordering': ['-fecha', 'taller', 'alumno'],
            },
        ),
        migrations.CreateModel(
            name='SesionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('R', 'Realizada'), ('F', 'Feriado'), ('P', 'Profesor ausente'), ('O', 'Otro')], default='R', max_length=1)),
                ('motivo_extra', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
