# Generated by Django 5.2.1 on 2025-06-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0002_initial'),
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='talleres.taller'),
        ),
        migrations.AddField(
            model_name='sesiontaller',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='talleres.taller'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('taller', 'alumno', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='sesiontaller',
            unique_together={('taller', 'fecha')},
        ),
    ]
